/** Scene identifiers used for navigation. */
export const SceneId = Object.freeze({
  MAIN_MENU: "mainMenu",
  LOGIN: "login",
  DECK_SELECTION: "deckSelection",
  DECK_BUILDER: "deckBuilder",
  STARTER: "starter",
  COLLECTION: "collection",
  SHOP: "shop",
  ONLINE: "online",
  LEADERBOARD: "leaderboard",
  GAME_HISTORY: "gameHistory",
  LIVE_GAMES: "liveGames",
  REPLAY: "replay",
  TRADES: "trades",
  MARKET: "market",
  NOTIFICATIONS: "notifications",
  INFO: "info",
  MATCH: "match",
  ERROR: "error",
});
