/** Error codes returned by GameEngine.execute. Presentation maps them to messages. */
export const CommandError = Object.freeze({
  GAME_OVER: "GAME_OVER",
  INVALID_COMMAND: "INVALID_COMMAND",
  UNKNOWN_PLAYER: "UNKNOWN_PLAYER",
  UNSUPPORTED_COMMAND: "UNSUPPORTED_COMMAND",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  NOT_ALLOWED_IN_PHASE: "NOT_ALLOWED_IN_PHASE",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  CANNOT_AFFORD: "CANNOT_AFFORD",
  INVALID_TARGET: "INVALID_TARGET",
  ZONE_FULL: "ZONE_FULL",
  ENGINE_ERROR: "ENGINE_ERROR",
});
