/**
 * Commit-reveal of a game's randomness, decks and states
 * (docs/tcg/03-game-blockchain-protocol.md §5).
 *
 * Everything derives from one 32-byte game secret S, generated by the server
 * with a CSPRNG, published only as a commitment when the game is created and
 * revealed when it ends:
 *
 *   seed_c   = H("seed-commit", S)
 *   K        = H("seed", S ‖ E_0 ‖ E_1 ‖ utf8(gameId))      engine key; E_k = seat k's entropy
 *   first    = s0 if the lowest bit of K[0] is 0, else s1
 *   salt     = H("state-salt", S)
 *   sc       = H("state", salt ‖ utf8(canonical(digest)))
 *   deck_c_k = H("deck", H("deck-salt", S ‖ byte(k)) ‖ utf8(canonical(deck_k)))
 */
import { canonicalize } from "../canonical/CanonicalJson.js";
import { HashTag, bytesToHex, hexToBytes, isHexOfLength, taggedHash, taggedHashHex, utf8 } from "../crypto/hash.js";
import { CARD_ID_PATTERN, GAME_ID_PATTERN, LIMITS, SEATS, Seat } from "./constants.js";
import { ProtocolError } from "./ProtocolError.js";

/**
 * @param {unknown} secret
 * @returns {Uint8Array}
 */
function secretBytes(secret) {
  if (!isHexOfLength(secret, LIMITS.SECRET_BYTES)) {
    throw new ProtocolError("the game secret must be 32 bytes as lowercase hex");
  }
  return hexToBytes(/** @type {string} */ (secret));
}

/**
 * @param {string} secret
 * @returns {string}
 */
export function seedCommitment(secret) {
  return taggedHashHex(HashTag.SEED_COMMIT, secretBytes(secret));
}

/**
 * The engine key K.
 * @param {{ secret: string, entropies: readonly string[], gameId: string }} inputs entropies in seat order
 * @returns {string} 64 lowercase hex characters
 */
export function deriveEngineSeed({ secret, entropies, gameId }) {
  if (!Array.isArray(entropies) || entropies.length !== SEATS.length || !entropies.every((entropy) => isHexOfLength(entropy, LIMITS.ENTROPY_BYTES))) {
    throw new ProtocolError(`entropies must be ${SEATS.length} values of ${LIMITS.ENTROPY_BYTES} bytes as lowercase hex`);
  }
  if (typeof gameId !== "string" || !GAME_ID_PATTERN.test(gameId)) {
    throw new ProtocolError("invalid game id");
  }
  return taggedHashHex(HashTag.SEED, secretBytes(secret), ...entropies.map(hexToBytes), utf8(gameId));
}

/**
 * @param {string} engineSeed K
 * @returns {string} the seat that plays first
 */
export function firstSeatFor(engineSeed) {
  if (!isHexOfLength(engineSeed, LIMITS.SECRET_BYTES)) {
    throw new ProtocolError("the engine seed must be 32 bytes as lowercase hex");
  }
  return (hexToBytes(engineSeed)[0] & 1) === 0 ? Seat.S0 : Seat.S1;
}

/**
 * @param {string} secret
 * @returns {string}
 */
export function stateSalt(secret) {
  return taggedHashHex(HashTag.STATE_SALT, secretBytes(secret));
}

/**
 * @param {string} salt from stateSalt()
 * @param {unknown} digest the engine's state digest (canonical data)
 * @returns {string}
 */
export function stateCommitment(salt, digest) {
  if (!isHexOfLength(salt, LIMITS.SECRET_BYTES)) {
    throw new ProtocolError("the state salt must be 32 bytes as lowercase hex");
  }
  return taggedHashHex(HashTag.STATE, hexToBytes(salt), utf8(canonicalize(digest)));
}

/**
 * A deck in its canonical revealed form: [["card_id", count], …] sorted by card id,
 * with duplicate ids merged.
 * @param {readonly ({ cardId: string, count: number } | readonly [string, number])[]} entries
 * @returns {readonly (readonly [string, number])[]}
 */
export function canonicalDeck(entries) {
  const counts = new Map();
  for (const entry of entries) {
    const [cardId, count] = Array.isArray(entry) ? entry : [entry.cardId, entry.count];
    if (typeof cardId !== "string" || !CARD_ID_PATTERN.test(cardId) || !Number.isSafeInteger(count) || count < 1) {
      throw new ProtocolError(`invalid deck entry ${JSON.stringify(entry)}`);
    }
    counts.set(cardId, (counts.get(cardId) ?? 0) + count);
  }
  if (counts.size === 0) {
    throw new ProtocolError("a deck cannot be empty");
  }
  return Object.freeze(
    [...counts]
      .sort(([left], [right]) => (left < right ? -1 : 1))
      .map(([cardId, count]) => Object.freeze([cardId, count])),
  );
}

/**
 * @param {string} secret
 * @param {number} seatIndex 0 or 1
 * @param {readonly ({ cardId: string, count: number } | readonly [string, number])[]} deck
 * @returns {string}
 */
export function deckCommitment(secret, seatIndex, deck) {
  if (!Number.isInteger(seatIndex) || seatIndex < 0 || seatIndex >= SEATS.length) {
    throw new ProtocolError("invalid seat index");
  }
  const salt = taggedHash(HashTag.DECK_SALT, secretBytes(secret), new Uint8Array([seatIndex]));
  return taggedHashHex(HashTag.DECK, salt, utf8(canonicalize(canonicalDeck(deck))));
}

/**
 * Turns random bytes from a CSPRNG into a game secret. The protocol does not
 * generate randomness itself; callers pass `crypto.getRandomValues` output.
 * @param {Uint8Array} bytes exactly 32 bytes
 * @returns {string}
 */
export function secretFromBytes(bytes) {
  if (!(bytes instanceof Uint8Array) || bytes.length !== LIMITS.SECRET_BYTES) {
    throw new ProtocolError("a game secret needs exactly 32 random bytes");
  }
  return bytesToHex(bytes);
}
